"""add program to review and update __repre__ function value

Revision ID: dfa449c81286
Revises: 8c6bfcf182ed
Create Date: 2023-03-28 09:13:29.504840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa449c81286'
down_revision = '8c6bfcf182ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('program', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'program')
    # ### end Alembic commands ###
